продолжаем тестирование. в ходе тестов выявлено, что не работают методы Update и Delete, выдают ошибку System.InvalidOperationException
System.InvalidOperationException: "The instance of entity type 'Category' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values."